
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOT EQUALS FMT_PRINTLN FUNC IDENTIFIER IMPORT LBRACE LPAREN MAIN NUMBER PACKAGE PLUS RBRACE RPAREN SEMICOLON STRINGprogram : PACKAGE IDENTIFIER SEMICOLON import_decls func_declsimport_decls : IMPORT STRING SEMICOLONfunc_decls : FUNC MAIN LPAREN RPAREN LBRACE stmt_list RBRACEstmt_list : stmt_list stmt\n                 | stmtstmt : FMT_PRINTLN LPAREN STRING RPAREN SEMICOLON'
    
_lr_action_items = {'PACKAGE':([0,],[2,]),'$end':([1,7,18,],[0,-1,-3,]),'IDENTIFIER':([2,],[3,]),'SEMICOLON':([3,9,22,],[4,11,23,]),'IMPORT':([4,],[6,]),'FUNC':([5,11,],[8,-2,]),'STRING':([6,20,],[9,21,]),'MAIN':([8,],[10,]),'LPAREN':([10,17,],[12,20,]),'RPAREN':([12,21,],[13,22,]),'LBRACE':([13,],[14,]),'FMT_PRINTLN':([14,15,16,19,23,],[17,17,-5,-4,-6,]),'RBRACE':([15,16,19,23,],[18,-5,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'import_decls':([4,],[5,]),'func_decls':([5,],[7,]),'stmt_list':([14,],[15,]),'stmt':([14,15,],[16,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PACKAGE IDENTIFIER SEMICOLON import_decls func_decls','program',5,'p_program','yacc.py',6),
  ('import_decls -> IMPORT STRING SEMICOLON','import_decls',3,'p_import_decls','yacc.py',10),
  ('func_decls -> FUNC MAIN LPAREN RPAREN LBRACE stmt_list RBRACE','func_decls',7,'p_func_decls','yacc.py',14),
  ('stmt_list -> stmt_list stmt','stmt_list',2,'p_stmt_list','yacc.py',18),
  ('stmt_list -> stmt','stmt_list',1,'p_stmt_list','yacc.py',19),
  ('stmt -> FMT_PRINTLN LPAREN STRING RPAREN SEMICOLON','stmt',5,'p_stmt','yacc.py',26),
]
